Repository dashinja/recipeciprocity, pull requests merged in 2019-01, with the labels that each got.

#47 Update Bootstrap version to current
  index.html
  recipes.html
  submissions.html
Labels: enhancement

#51 Working index
  assets/css/style.css
  assets/images/placeholder.jpg
  assets/javaScript/app.js
  index.html
  submissions.html
Labels: enhancement

#52 Recipepopulation
  assets/javaScript/app.js
  assets/javaScript/form-validation/form-validation.js
  recipes.html
Labels: enhancement

#53 Jsfile
  assets/javaScript/app.js
  assets/javaScript/form-validation/form-validation.js
  index.html
Labels: enhancement

#58 Voice on demand
  assets/javaScript/app.js
  assets/javaScript/form-validation/form-validation.js
  recipes.html
  submissions.html
Labels: enhancement

#68 Jsfile
  assets/javaScript/app.js
  assets/javaScript/form-validation/form-validation.js
Labels: bug

#69 bug: remove repeat element sections
  recipes.html
Labels: invalid

#70 Owl carousel
  assets/javaScript/app.js
  assets/javaScript/owlcarousel/LICENSE
  assets/javaScript/owlcarousel/README.md
  assets/javaScript/owlcarousel/assets/ajax-loader.gif
  assets/javaScript/owlcarousel/assets/owl.carousel.css
  assets/javaScript/owlcarousel/assets/owl.carousel.min.css
  assets/javaScript/owlcarousel/assets/owl.theme.default.css
  assets/javaScript/owlcarousel/assets/owl.theme.default.min.css
  assets/javaScript/owlcarousel/assets/owl.theme.green.css
  assets/javaScript/owlcarousel/assets/owl.theme.green.min.css
  assets/javaScript/owlcarousel/assets/owl.video.play.png
  assets/javaScript/owlcarousel/owl.carousel.js
  assets/javaScript/owlcarousel/owl.carousel.min.js
  index.html
Labels: enhancement

#74 footer border, recipe margin-bottom
  assets/css/style.css
  index.html
  recipes.html
Labels: enhancement

#75 footer overflow hidden
  assets/css/style.css
Labels: bug, enhancement

#77 Fixed JS bugs total
  assets/javaScript/app.js
  assets/javaScript/form-validation/form-validation.js
  index.html
  recipes.html
Labels: bug

#81 Jsfile
  assets/javaScript/app.js
Labels: bug

#88 are*
  assets/css/style.css
  index.html
Labels: invalid

#89 limited results to a variable on recipe page
  assets/javaScript/app.js
Labels: enhancement

#91 Fresh edit
  assets/css/style.css
  assets/javaScript/app.js
  assets/javaScript/form-validation/form-validation.js
  index.html
  submissions.html
Labels: bug

#94 ipad media queries
  assets/css/style.css
  index.html
Labels: enhancement

#96 Limiter - Works in all ways.
  assets/javaScript/app.js
  recipes.html
Labels: bug

#98 User confirmation below submit button after successful recipe submission
  assets/css/style.css
  assets/javaScript/form-validation/form-validation.js
  submissions.html
Labels: bug

#104 fix(recipe.html): Show More button press returns to newest card location
  assets/javaScript/app.js
  recipes.html
Labels: bug, invalid
